// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.28.3
// source: orchestrator.proto

package orchestrator

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Orchestrator_CreateCube_FullMethodName  = "/orchestrator.Orchestrator/CreateCube"
	Orchestrator_GetAllCubes_FullMethodName = "/orchestrator.Orchestrator/GetAllCubes"
	Orchestrator_GetCube_FullMethodName     = "/orchestrator.Orchestrator/GetCube"
	Orchestrator_DeleteCube_FullMethodName  = "/orchestrator.Orchestrator/DeleteCube"
	Orchestrator_UpdateCube_FullMethodName  = "/orchestrator.Orchestrator/UpdateCube"
)

// OrchestratorClient is the client API for Orchestrator service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type OrchestratorClient interface {
	CreateCube(ctx context.Context, in *CreateCubeRequest, opts ...grpc.CallOption) (*CreateCubeResponse, error)
	GetAllCubes(ctx context.Context, in *GetAllCubesRequest, opts ...grpc.CallOption) (*GetAllCubesResponse, error)
	GetCube(ctx context.Context, in *GetCubeRequest, opts ...grpc.CallOption) (*GetCubeResponse, error)
	DeleteCube(ctx context.Context, in *DeleteCubeRequest, opts ...grpc.CallOption) (*DeleteCubeResponse, error)
	UpdateCube(ctx context.Context, in *UpdateCubeRequest, opts ...grpc.CallOption) (*UpdateCubeResponse, error)
}

type orchestratorClient struct {
	cc grpc.ClientConnInterface
}

func NewOrchestratorClient(cc grpc.ClientConnInterface) OrchestratorClient {
	return &orchestratorClient{cc}
}

func (c *orchestratorClient) CreateCube(ctx context.Context, in *CreateCubeRequest, opts ...grpc.CallOption) (*CreateCubeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateCubeResponse)
	err := c.cc.Invoke(ctx, Orchestrator_CreateCube_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *orchestratorClient) GetAllCubes(ctx context.Context, in *GetAllCubesRequest, opts ...grpc.CallOption) (*GetAllCubesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetAllCubesResponse)
	err := c.cc.Invoke(ctx, Orchestrator_GetAllCubes_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *orchestratorClient) GetCube(ctx context.Context, in *GetCubeRequest, opts ...grpc.CallOption) (*GetCubeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetCubeResponse)
	err := c.cc.Invoke(ctx, Orchestrator_GetCube_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *orchestratorClient) DeleteCube(ctx context.Context, in *DeleteCubeRequest, opts ...grpc.CallOption) (*DeleteCubeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteCubeResponse)
	err := c.cc.Invoke(ctx, Orchestrator_DeleteCube_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *orchestratorClient) UpdateCube(ctx context.Context, in *UpdateCubeRequest, opts ...grpc.CallOption) (*UpdateCubeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateCubeResponse)
	err := c.cc.Invoke(ctx, Orchestrator_UpdateCube_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// OrchestratorServer is the server API for Orchestrator service.
// All implementations must embed UnimplementedOrchestratorServer
// for forward compatibility.
type OrchestratorServer interface {
	CreateCube(context.Context, *CreateCubeRequest) (*CreateCubeResponse, error)
	GetAllCubes(context.Context, *GetAllCubesRequest) (*GetAllCubesResponse, error)
	GetCube(context.Context, *GetCubeRequest) (*GetCubeResponse, error)
	DeleteCube(context.Context, *DeleteCubeRequest) (*DeleteCubeResponse, error)
	UpdateCube(context.Context, *UpdateCubeRequest) (*UpdateCubeResponse, error)
	mustEmbedUnimplementedOrchestratorServer()
}

// UnimplementedOrchestratorServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedOrchestratorServer struct{}

func (UnimplementedOrchestratorServer) CreateCube(context.Context, *CreateCubeRequest) (*CreateCubeResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateCube not implemented")
}
func (UnimplementedOrchestratorServer) GetAllCubes(context.Context, *GetAllCubesRequest) (*GetAllCubesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetAllCubes not implemented")
}
func (UnimplementedOrchestratorServer) GetCube(context.Context, *GetCubeRequest) (*GetCubeResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetCube not implemented")
}
func (UnimplementedOrchestratorServer) DeleteCube(context.Context, *DeleteCubeRequest) (*DeleteCubeResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteCube not implemented")
}
func (UnimplementedOrchestratorServer) UpdateCube(context.Context, *UpdateCubeRequest) (*UpdateCubeResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateCube not implemented")
}
func (UnimplementedOrchestratorServer) mustEmbedUnimplementedOrchestratorServer() {}
func (UnimplementedOrchestratorServer) testEmbeddedByValue()                      {}

// UnsafeOrchestratorServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to OrchestratorServer will
// result in compilation errors.
type UnsafeOrchestratorServer interface {
	mustEmbedUnimplementedOrchestratorServer()
}

func RegisterOrchestratorServer(s grpc.ServiceRegistrar, srv OrchestratorServer) {
	// If the following call pancis, it indicates UnimplementedOrchestratorServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Orchestrator_ServiceDesc, srv)
}

func _Orchestrator_CreateCube_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateCubeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OrchestratorServer).CreateCube(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Orchestrator_CreateCube_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OrchestratorServer).CreateCube(ctx, req.(*CreateCubeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Orchestrator_GetAllCubes_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetAllCubesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OrchestratorServer).GetAllCubes(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Orchestrator_GetAllCubes_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OrchestratorServer).GetAllCubes(ctx, req.(*GetAllCubesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Orchestrator_GetCube_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetCubeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OrchestratorServer).GetCube(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Orchestrator_GetCube_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OrchestratorServer).GetCube(ctx, req.(*GetCubeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Orchestrator_DeleteCube_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteCubeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OrchestratorServer).DeleteCube(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Orchestrator_DeleteCube_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OrchestratorServer).DeleteCube(ctx, req.(*DeleteCubeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Orchestrator_UpdateCube_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateCubeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OrchestratorServer).UpdateCube(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Orchestrator_UpdateCube_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OrchestratorServer).UpdateCube(ctx, req.(*UpdateCubeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Orchestrator_ServiceDesc is the grpc.ServiceDesc for Orchestrator service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Orchestrator_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "orchestrator.Orchestrator",
	HandlerType: (*OrchestratorServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateCube",
			Handler:    _Orchestrator_CreateCube_Handler,
		},
		{
			MethodName: "GetAllCubes",
			Handler:    _Orchestrator_GetAllCubes_Handler,
		},
		{
			MethodName: "GetCube",
			Handler:    _Orchestrator_GetCube_Handler,
		},
		{
			MethodName: "DeleteCube",
			Handler:    _Orchestrator_DeleteCube_Handler,
		},
		{
			MethodName: "UpdateCube",
			Handler:    _Orchestrator_UpdateCube_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "orchestrator.proto",
}
