# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.20'

    - name: Prepare for building
      run: go install fyne.io/fyne/v2/cmd/fyne@latest && go install github.com/fyne-io/fyne-cross@latest

    - name: Build for Windows
      run: fyne-cross windows -icon assets/android.png -arch=* -app-id com.virusrpi.cubus

    - name: Build for Linux
      run: fyne-cross linux -icon assets/android.png -arch=* -app-id com.virusrpi.cubus

    - name: Build for Android
      run: fyne-cross android -icon assets/android.png -arch=* -app-id com.virusrpi.cubus

    - name: Saving Artifacts
      uses: actions/upload-artifact@v2
      with:
        name: artifacts
        path: ./fyne-cross/dist/*
